# -*- coding: utf-8 -*-
"""pip1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqniHXR91z0-qR9FNrCeLdpcLri3kIZT
"""

from flask import Flask, jsonify
app = Flask(__name__)

@app.route('/', methods=['GET'])
def hello_world():
  json_respone ={
      'status_code' :200,
      'description' : "Menyapa Hello World",
      'data' : "Hello World"
  }

  respone_data  = jsonify(json_respone)
  return respone_data

if __name__== '__main__':
  app.run()